<?php

namespace Vend\Api;

use Offshoot\HttpClient;

class Client
{

    const API_URI = 'https://%s.vendhq.com/api';

    /** @var string */
    protected $storeName;

    /**
     * the permanenet access token generated by Vend
     * @var string
     */
    protected $accessToken;

    /**
     * the http client used to make requests to the Vend api
     * @var HttpClient
     */
    protected $httpClient;

    /**
     * initialize the API client
     * @param HttpClient $client
     */
    public function __construct(HttpClient $client)
    {
        $this->httpClient = $client;
    }

    /**
     * set the store name
     * @param string $storeName
     */
    public function setStoreName($storeName)
    {
        $this->storeName = $storeName;
    }

    /**
     * set the permanent access token returned by Vend API
     * @param string $token
     */
    public function setAccessToken($token)
    {
        $this->accessToken = $token;
    }

    /**
     * make a GET request to the Vend API
     * @param string $resource
     * @param array $params
     * @return \stdClass
     */
    public function get($resource, array $params = array())
    {
        return $this->makeApiRequest($resource, $params);
    }

    /**
     * make a POST request to the Vend API
     * @param string $resource
     * @param array $data
     * @return \stdClass
     */
    public function post($resource, array $data = array())
    {
        return $this->makeApiRequest($resource, $data, HttpClient::POST);
    }

    /**
     * get the store name
     * @return string
     */
    protected function getStoreName()
    {
        return $this->storeName;
    }

    /**
     * get the base URI for the api
     * @return string
     */
    protected function getApiUri()
    {
        return sprintf(self::API_URI, $this->getStoreName());
    }

    /**
     * make a generic request to the api
     * @param string $resource
     * @param array $params
     * @param string $method
     * @return \stdClass
     */
    protected function makeApiRequest(
        $resource, array $params = array(), $method = HttpClient::GET
    ) {

        $uri = $this->getApiUri() . '/' . ltrim($resource, '/');

        $this->getHttpClient()->addHeader(
            'Authorization',
            "Bearer {$this->getAccessToken()}"
        );

        switch ($method) {
            case HttpClient::GET:
                $response = $this->getHttpClient()->get($uri, $params);
                break;
            case HttpClient::POST:
                $data = json_encode($params);
                $response = $this->getHttpClient()->post($uri, $data);
                break;
            case 'PUT':
            case 'DELETE':
            default:
                throw new \RuntimeException(
                    'Currently only "GET" and "POST" are supported. "PUT" and '
                    . '"DELETE" functionality is currently under development'
                );
        }

        $response = json_decode($response);

        if (isset($response->errors)) {
            throw new \RuntimeException($response->errors);
        }

        return $response;

    }

    /**
     * get the HTTP Client
     * @return HttpClient
     */
    protected function getHttpClient()
    {
        return $this->httpClient;
    }

    /**
     * get the access token
     * @return string
     */
    protected function getAccessToken()
    {
        return $this->accessToken;
    }

    /**
     * get the store name
     * @return string
     */
    protected function getStoreName()
    {
        return $this->storeName;
    }

}
